/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 35.3.0 Tue Jan  5 22:10:29 2021.
 */

#include <string.h>

#include "canxian.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int canxian_imu1_pack(
    uint8_t *dst_p,
    const struct canxian_imu1_t *src_p,
    size_t size)
{
    uint16_t acc_x;
    uint32_t gyro_x;
    uint32_t gyro_y;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    gyro_x = (uint32_t)src_p->gyro_x;
    dst_p[0] |= pack_right_shift_u32(gyro_x, 16u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(gyro_x, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(gyro_x, 0u, 0xffu);
    gyro_y = (uint32_t)src_p->gyro_y;
    dst_p[3] |= pack_right_shift_u32(gyro_y, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(gyro_y, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u32(gyro_y, 0u, 0xffu);
    acc_x = (uint16_t)src_p->acc_x;
    dst_p[6] |= pack_right_shift_u16(acc_x, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(acc_x, 0u, 0xffu);

    return (8);
}

int canxian_imu1_unpack(
    struct canxian_imu1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acc_x;
    uint32_t gyro_x;
    uint32_t gyro_y;

    if (size < 8u) {
        return (-EINVAL);
    }

    gyro_x = unpack_left_shift_u32(src_p[0], 16u, 0xffu);
    gyro_x |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    gyro_x |= unpack_right_shift_u32(src_p[2], 0u, 0xffu);

    if ((gyro_x & (1u << 23)) != 0u) {
        gyro_x |= 0xff000000u;
    }

    dst_p->gyro_x = (int32_t)gyro_x;
    gyro_y = unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    gyro_y |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    gyro_y |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);

    if ((gyro_y & (1u << 23)) != 0u) {
        gyro_y |= 0xff000000u;
    }

    dst_p->gyro_y = (int32_t)gyro_y;
    acc_x = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    acc_x |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->acc_x = (int16_t)acc_x;

    return (0);
}

int32_t canxian_imu1_gyro_x_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double canxian_imu1_gyro_x_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool canxian_imu1_gyro_x_is_in_range(int32_t value)
{
    return ((value >= -500000) && (value <= 500000));
}

int32_t canxian_imu1_gyro_y_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double canxian_imu1_gyro_y_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool canxian_imu1_gyro_y_is_in_range(int32_t value)
{
    return ((value >= -500000) && (value <= 500000));
}

int16_t canxian_imu1_acc_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double canxian_imu1_acc_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool canxian_imu1_acc_x_is_in_range(int16_t value)
{
    return ((value >= -10000) && (value <= 10000));
}

int canxian_imu2_pack(
    uint8_t *dst_p,
    const struct canxian_imu2_t *src_p,
    size_t size)
{
    uint16_t acc_y;
    uint16_t acc_z;
    uint32_t gyro_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    gyro_z = (uint32_t)src_p->gyro_z;
    dst_p[0] |= pack_right_shift_u32(gyro_z, 16u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(gyro_z, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(gyro_z, 0u, 0xffu);
    acc_y = (uint16_t)src_p->acc_y;
    dst_p[3] |= pack_right_shift_u16(acc_y, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(acc_y, 0u, 0xffu);
    acc_z = (uint16_t)src_p->acc_z;
    dst_p[5] |= pack_right_shift_u16(acc_z, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(acc_z, 0u, 0xffu);

    return (8);
}

int canxian_imu2_unpack(
    struct canxian_imu2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acc_y;
    uint16_t acc_z;
    uint32_t gyro_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    gyro_z = unpack_left_shift_u32(src_p[0], 16u, 0xffu);
    gyro_z |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    gyro_z |= unpack_right_shift_u32(src_p[2], 0u, 0xffu);

    if ((gyro_z & (1u << 23)) != 0u) {
        gyro_z |= 0xff000000u;
    }

    dst_p->gyro_z = (int32_t)gyro_z;
    acc_y = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    acc_y |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->acc_y = (int16_t)acc_y;
    acc_z = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    acc_z |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->acc_z = (int16_t)acc_z;

    return (0);
}

int32_t canxian_imu2_gyro_z_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double canxian_imu2_gyro_z_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool canxian_imu2_gyro_z_is_in_range(int32_t value)
{
    return ((value >= -500000) && (value <= 500000));
}

int16_t canxian_imu2_acc_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double canxian_imu2_acc_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool canxian_imu2_acc_y_is_in_range(int16_t value)
{
    return ((value >= -10000) && (value <= 10000));
}

int16_t canxian_imu2_acc_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double canxian_imu2_acc_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool canxian_imu2_acc_z_is_in_range(int16_t value)
{
    return ((value >= -10000) && (value <= 10000));
}

int canxian_acc_1_pack(
    uint8_t *dst_p,
    const struct canxian_acc_1_t *src_p,
    size_t size)
{
    uint16_t acc_x_1;
    uint16_t acc_y_1;
    uint16_t acc_z_1;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    acc_x_1 = (uint16_t)src_p->acc_x_1;
    dst_p[0] |= pack_right_shift_u16(acc_x_1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(acc_x_1, 0u, 0xffu);
    acc_y_1 = (uint16_t)src_p->acc_y_1;
    dst_p[2] |= pack_right_shift_u16(acc_y_1, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(acc_y_1, 0u, 0xffu);
    acc_z_1 = (uint16_t)src_p->acc_z_1;
    dst_p[4] |= pack_right_shift_u16(acc_z_1, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(acc_z_1, 0u, 0xffu);

    return (8);
}

int canxian_acc_1_unpack(
    struct canxian_acc_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acc_x_1;
    uint16_t acc_y_1;
    uint16_t acc_z_1;

    if (size < 8u) {
        return (-EINVAL);
    }

    acc_x_1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    acc_x_1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_x_1 = (int16_t)acc_x_1;
    acc_y_1 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    acc_y_1 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_y_1 = (int16_t)acc_y_1;
    acc_z_1 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    acc_z_1 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_z_1 = (int16_t)acc_z_1;

    return (0);
}

int16_t canxian_acc_1_acc_x_1_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_1_acc_x_1_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_1_acc_x_1_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_1_acc_y_1_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_1_acc_y_1_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_1_acc_y_1_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_1_acc_z_1_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_1_acc_z_1_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_1_acc_z_1_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int canxian_acc_2_pack(
    uint8_t *dst_p,
    const struct canxian_acc_2_t *src_p,
    size_t size)
{
    uint16_t acc_x_2;
    uint16_t acc_y_2;
    uint16_t acc_z_2;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    acc_x_2 = (uint16_t)src_p->acc_x_2;
    dst_p[0] |= pack_right_shift_u16(acc_x_2, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(acc_x_2, 0u, 0xffu);
    acc_y_2 = (uint16_t)src_p->acc_y_2;
    dst_p[2] |= pack_right_shift_u16(acc_y_2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(acc_y_2, 0u, 0xffu);
    acc_z_2 = (uint16_t)src_p->acc_z_2;
    dst_p[4] |= pack_right_shift_u16(acc_z_2, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(acc_z_2, 0u, 0xffu);

    return (8);
}

int canxian_acc_2_unpack(
    struct canxian_acc_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acc_x_2;
    uint16_t acc_y_2;
    uint16_t acc_z_2;

    if (size < 8u) {
        return (-EINVAL);
    }

    acc_x_2 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    acc_x_2 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_x_2 = (int16_t)acc_x_2;
    acc_y_2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    acc_y_2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_y_2 = (int16_t)acc_y_2;
    acc_z_2 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    acc_z_2 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_z_2 = (int16_t)acc_z_2;

    return (0);
}

int16_t canxian_acc_2_acc_x_2_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_2_acc_x_2_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_2_acc_x_2_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_2_acc_y_2_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_2_acc_y_2_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_2_acc_y_2_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_2_acc_z_2_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_2_acc_z_2_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_2_acc_z_2_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int canxian_acc_3_pack(
    uint8_t *dst_p,
    const struct canxian_acc_3_t *src_p,
    size_t size)
{
    uint16_t acc_x_3;
    uint16_t acc_y_3;
    uint16_t acc_z_3;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    acc_x_3 = (uint16_t)src_p->acc_x_3;
    dst_p[0] |= pack_right_shift_u16(acc_x_3, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(acc_x_3, 0u, 0xffu);
    acc_y_3 = (uint16_t)src_p->acc_y_3;
    dst_p[2] |= pack_right_shift_u16(acc_y_3, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(acc_y_3, 0u, 0xffu);
    acc_z_3 = (uint16_t)src_p->acc_z_3;
    dst_p[4] |= pack_right_shift_u16(acc_z_3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(acc_z_3, 0u, 0xffu);

    return (8);
}

int canxian_acc_3_unpack(
    struct canxian_acc_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acc_x_3;
    uint16_t acc_y_3;
    uint16_t acc_z_3;

    if (size < 8u) {
        return (-EINVAL);
    }

    acc_x_3 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    acc_x_3 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_x_3 = (int16_t)acc_x_3;
    acc_y_3 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    acc_y_3 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_y_3 = (int16_t)acc_y_3;
    acc_z_3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    acc_z_3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_z_3 = (int16_t)acc_z_3;

    return (0);
}

int16_t canxian_acc_3_acc_x_3_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_3_acc_x_3_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_3_acc_x_3_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_3_acc_y_3_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_3_acc_y_3_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_3_acc_y_3_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_3_acc_z_3_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_3_acc_z_3_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_3_acc_z_3_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int canxian_acc_4_pack(
    uint8_t *dst_p,
    const struct canxian_acc_4_t *src_p,
    size_t size)
{
    uint16_t acc_x_4;
    uint16_t acc_y_4;
    uint16_t acc_z_4;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    acc_x_4 = (uint16_t)src_p->acc_x_4;
    dst_p[0] |= pack_right_shift_u16(acc_x_4, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(acc_x_4, 0u, 0xffu);
    acc_y_4 = (uint16_t)src_p->acc_y_4;
    dst_p[2] |= pack_right_shift_u16(acc_y_4, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(acc_y_4, 0u, 0xffu);
    acc_z_4 = (uint16_t)src_p->acc_z_4;
    dst_p[4] |= pack_right_shift_u16(acc_z_4, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(acc_z_4, 0u, 0xffu);

    return (8);
}

int canxian_acc_4_unpack(
    struct canxian_acc_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acc_x_4;
    uint16_t acc_y_4;
    uint16_t acc_z_4;

    if (size < 8u) {
        return (-EINVAL);
    }

    acc_x_4 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    acc_x_4 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_x_4 = (int16_t)acc_x_4;
    acc_y_4 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    acc_y_4 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_y_4 = (int16_t)acc_y_4;
    acc_z_4 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    acc_z_4 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_z_4 = (int16_t)acc_z_4;

    return (0);
}

int16_t canxian_acc_4_acc_x_4_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_4_acc_x_4_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_4_acc_x_4_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_4_acc_y_4_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_4_acc_y_4_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_4_acc_y_4_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_4_acc_z_4_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_4_acc_z_4_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_4_acc_z_4_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int canxian_acc_5_pack(
    uint8_t *dst_p,
    const struct canxian_acc_5_t *src_p,
    size_t size)
{
    uint16_t acc_x_5;
    uint16_t acc_y_5;
    uint16_t acc_z_5;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    acc_x_5 = (uint16_t)src_p->acc_x_5;
    dst_p[0] |= pack_right_shift_u16(acc_x_5, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(acc_x_5, 0u, 0xffu);
    acc_y_5 = (uint16_t)src_p->acc_y_5;
    dst_p[2] |= pack_right_shift_u16(acc_y_5, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(acc_y_5, 0u, 0xffu);
    acc_z_5 = (uint16_t)src_p->acc_z_5;
    dst_p[4] |= pack_right_shift_u16(acc_z_5, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(acc_z_5, 0u, 0xffu);

    return (8);
}

int canxian_acc_5_unpack(
    struct canxian_acc_5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acc_x_5;
    uint16_t acc_y_5;
    uint16_t acc_z_5;

    if (size < 8u) {
        return (-EINVAL);
    }

    acc_x_5 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    acc_x_5 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_x_5 = (int16_t)acc_x_5;
    acc_y_5 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    acc_y_5 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_y_5 = (int16_t)acc_y_5;
    acc_z_5 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    acc_z_5 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_z_5 = (int16_t)acc_z_5;

    return (0);
}

int16_t canxian_acc_5_acc_x_5_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_5_acc_x_5_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_5_acc_x_5_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_5_acc_y_5_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_5_acc_y_5_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_5_acc_y_5_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t canxian_acc_5_acc_z_5_encode(double value)
{
    return (int16_t)(value / 0.001333333);
}

double canxian_acc_5_acc_z_5_decode(int16_t value)
{
    return ((double)value * 0.001333333);
}

bool canxian_acc_5_acc_z_5_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}


int DBC_Decode(VCI_CAN_OBJ* R_message,int R_length,double *matrix, DBC_INFO* dbc_info)
{
    //printf("I am in~\n\r");
    int matrix_column_value=dbc_info->matrix_column_value;
    int matrix_row=dbc_info->matrix_row;
    int filled_column=dbc_info->filled_column;
    int matrix_row_value=dbc_info->matrix_row_value;
    int timestamp=dbc_info->timestamp;
    int ReturnValue;
    //ReturnValue=R_length;
    //int R_length=matrix_row_value/3;

    for(int i=0;i<R_length;i++)
    {
        VCI_CAN_OBJ temp_message=R_message[i];


        if (temp_message.ID==selected_ID)
        {
            if (selected_ID==0x181u || selected_ID==0x182u selected_ID==0x183u || selected_ID==0x184u || selected_ID==0x185u)
            {
                matrix[matrix_row*matrix_column_value+0]=canxian_acc_1_acc_x_1_decode((temp_message.Data[0]<<8)+(temp_message.Data[1]));
                matrix[matrix_row*matrix_column_value+1]=canxian_acc_1_acc_y_1_decode((temp_message.Data[2]<<8)+(temp_message.Data[3]));
                matrix[matrix_row*matrix_column_value+2]=canxian_acc_1_acc_z_1_decode((temp_message.Data[4]<<8)+(temp_message.Data[5]));  
                 
            }
            else if (selected_ID==0x18au)
            {
                matrix[matrix_row*matrix_column_value+0]=canxian_imu1_gyro_x_decode((temp_message.Data[0]<<16)+(temp_message.Data[1]<<8)+(temp_message.Data[2]));
                matrix[matrix_row*matrix_column_value+1]=canxian_imu1_gyro_y_decode((temp_message.Data[3]<<16)+(temp_message.Data[4]<<8)+(temp_message.Data[5]));
                matrix[matrix_row*matrix_column_value+2]=canxian_imu1_acc_x_decode((temp_message.Data[6]<<8)+(temp_message.Data[7])); 
            }

            else if (selected_ID==0x18bu)
            {
                matrix[matrix_row*matrix_column_value+0]=canxian_imu2_gyro_z_decode((temp_message.Data[0]<<16)+(temp_message.Data[1]<<8)+(temp_message.Data[2]));
                matrix[matrix_row*matrix_column_value+1]=canxian_imu1_acc_y_decode((temp_message.Data[3]<<8)+(temp_message.Data[4])); 
                matrix[matrix_row*matrix_column_value+2]=canxian_imu1_acc_z_decode((temp_message.Data[5]<<8)+(temp_message.Data[6])); 
            }
            matrix_row++;

        }
             

        //filled_column+=3;
        if(matrix_row==matrix_row_value)
        {
            break;

        
        }


    }

    dbc_info->matrix_column_value=matrix_column_value;
    dbc_info->matrix_row=matrix_row;
    dbc_info->filled_column=filled_column;
    dbc_info->matrix_row_value=matrix_row_value;
    dbc_info->timestamp=timestamp;
    return -1;

}